ci:
  autofix_prs: true
  autoupdate_schedule: monthly

files: "monster_mess.c"

repos:
  # C style
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.0
    hooks:
      - id: clang-format
        types_or: [c]
